config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :cities
  resources :locations
  resources :posts
  # get '/travelgram', to: 'users#travelgram', as: "travelgram" 
  # get '/', to: 'users#travelgram'
  # post '/authenticate', to: "users#authenticate", as: "authenticate"
  resources :posts do
    resources :likes
  end 
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/login', to: 'sessions#destroy', as: "logout"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/search', to: 'posts#index', as: 'search'
  root 'sessions#new'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :posts, through: :likes
  has_many :posts, dependent: :destroy
  has_many :locations, through: :posts
  has_many :cities, through: :posts
  validates :username, :uniqueness => true 
  # :message =>  "Your account has been signed up, please log in with your existing account."
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_params, only: [:create, :update]
  before_action :require_login
  before_action :current_user
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      if params[:user][:password].empty? || params[:user][:password_confirmation].empty?
        flash[:danger] = "Password can't be blank."
      elsif params[:user][:password] != params[:user][:password_confirmation]
        flash[:danger] = "Passwords do not match."
      else
        flash[:danger] = "Your account has already been signed up, please log in with your existing account."
      end
      redirect_to new_user_path
    end
  end

  # def travelgram 
  # end

  # def authenticate
  #   @user = User.find_by(username: params[:user][:username], password: params[:user][:password])
  #   if User.find_by(username: params[:user][:username], password: params[:user][:password])
  #     redirect_to posts_path
  #   else
  #     flash[:new_user_message] = "No user information, please try log in again or create a new account"
  #     redirect_to "/"
  #   end
  # end

  def show 
    @user = User.find(params[:id])
    @posts = @user.posts.reverse
    @likes = @user.posts.map{ |post| post.likes}.flatten.count
    @post_count = @user.posts.count
    @location_count = @user.posts.map{ |post| post.location}.uniq.count
    @city_count = @user.posts.map{ |post| post.location.city}.uniq.count
  end

  def edit
    @user = User.find(params[:id])   
  end

  def update
    @user = User.find(params[:id])
    if User.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.delete
    redirect_to posts_path   
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :bio, :home_city, :password_confirmation)
  end

  def require_login
    if !session[:user_id]
      redirect_to login_path
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div id="updatebackground">
<div id="updatebody">
  <h1 class="newh1">Please update your profile info:</h1>
  <br>
  <br>
  <%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username, :class => "newinput inputsize" %><br>
    <br>
    <%= f.label :password %>
    <%= f.text_field :password, :class => "newinput inputsize" %><br>
    <br>
    <%= f.label :home_city %>
    <%= f.text_field :home_city, :class => "newinput inputsize" %><br>
    <br>
    <%= f.label :bio %>
    <%= f.text_area :bio, :class => "newinput inputsize" %><br>
    <br>
    <%= f.submit :class =>"inputbutton" %>
  <% end %>
</div>
</div>

app/views/users/new.html.erb
<div id="newuserbackground">
<div id="newuserbody">
  <%= flash[:danger] %>
  <%flash.clear%>
  <h1 class="newh1">Create a New User</h1>
  <br>
  <br>
  <%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username, :class => "newinput inputsize"%><br>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password, :class => "newinput inputsize" %><br>
    <br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => "newinput inputsize" %><br>
    <br>
    <%= f.label :home_city %>
    <%= f.text_field :home_city, :class => "newinput inputsize" %><br>
    <br>
    <%= f.label :bio %>
    <%= f.text_field :bio, :class => "newinput inputsize" %><br>
    <br>
    <br>
    <%= f.submit :class =>"inputbutton" %>
  <% end %>
</div>
</div>

app/views/users/show.html.erb
<div id="userbackground">
<div id="userbody">
<div class="grid-container">
  <div class="grid-item1" id="userinfo">
    <h1><%= @user.username %></h1><br>
    <h3>📍<%= @user.home_city.titleize %></h3>
    <h4 id="userbio"><%= @user.bio %></h4>
    <br>
    <h5>Total Posts: <%=@post_count%></h5>
    <h5>Total Likes: <%=@likes%></h5>
    <br>
    <h5><%=@user.username%> has been to <%=@location_count%> locations</h5>
    <h5>and <%=@city_count%> different cities</h5>
    <div class="buttons">
    <% if @user.id == session[:user_id] %>
    <div class="button">
      <%= button_to "Edit Profile", {:controller => :users,
      :action => 'edit', :id => @user.id}, :method => :get, :class => "inputbutton" %>
    </div>
    <div class="button">
      <%= button_to "Delete", {:controller => :users,
      :action => 'destroy', :id => @user.id}, :method => :delete, :class => "inputbutton", data: { confirm: 'Are you sure you want to leave us?' } %>
    </div>
    <%end%>
    </div>
  </div>

  <div class="grid-item2">
    <% @posts.each do |post| %>
      <div class="posts">
      <%=link_to image_tag(url_for(post.avatar),:class=>"image"), post_path(post) %><br>
      <div class="container">
        <div class="item1"><h4><%= post.caption %> &nbsp📍<%=link_to post.location.city.name.titleize, city_path(post.location.city)%></h4></div>
        <div class="item2"><h4>❤️ <%= post.likes.count %></h4></div>
      </div>
      </div>
    <% end %>
  </div>
</div>
</div>
</div>

app/views/users/travelgram.html.erb
<div class="loginbackground">
  <div class="loginbody">
    <%= flash[:new_user_message] %>
    <%= form_tag "/authenticate", method: "post" do %>
      <%= text_field_tag :'user[username]', placeholder: "Username" %><br>
      <%= text_field_tag :'user[password]', placeholder: "Password" %><br>
      <%= submit_tag "log in" %>
    <% end %>
    <h5>or</h5>
    <h5><%= link_to "create a new account", new_user_path %></h5>
  </div>
</div>