config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :cities
  resources :locations
  resources :posts
  # get '/travelgram', to: 'users#travelgram', as: "travelgram" 
  # get '/', to: 'users#travelgram'
  # post '/authenticate', to: "users#authenticate", as: "authenticate"
  resources :posts do
    resources :likes
  end 
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/login', to: 'sessions#destroy', as: "logout"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/search', to: 'posts#index', as: 'search'
  root 'sessions#new'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :location
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  has_one_attached :avatar
  attr_accessor :city_id
  validates :location_id, presence: true
  validates :avatar, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg']}
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_login
    before_action :current_user
    def index
        if params.has_key?(:q)
            array = search(params)
            final_array = []
            final_array << array[-1]
            final_array << array[-2]
            final_array << array[0..-3].shuffle
            @posts = final_array.flatten
        else
            array = Post.all
            final_array = []
            final_array << array[-1]
            final_array << array[-2]
            final_array << array[0..-3].shuffle
            @posts = final_array.flatten
        end
    end

    def new
        @post = Post.new
    end

    def create
        city_location_params(params)
        if params[:post][:user_id].to_i == current_user.id
            @post = Post.new(post_params)
            if @post.save
                redirect_to post_path(@post)
            else
                flash[:user_error] = "There was an error processing your request."
                @post = Post.new
                redirect_to new_post_path
            end
        else
            flash[:user_error] = "There was an error processing your request."
            @post = Post.new
            redirect_to new_post_path
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        city_location_params(params) 
        if params[:post][:user_id].to_i == current_user.id
            @post = Post.find(params[:id])
            params[:post][:avatar] = @post.avatar
            if @post.update(post_params)
                redirect_to post_path(@post)
            else
                flash[:user_error] = "There was an error processing your request."
                render :edit
            end
        else
            flash[:user_error] = "There was an error processing your request."
            @post = Post.find(params[:id])
            render :edit
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end



    private

    def city_location_params(params)
        city = params[:post][:city_id].downcase
        city_object = City.find_or_create_by(name: city)
        params[:post][:city_id] = city_object.id
        location = params[:post][:location_id].downcase
        location_object = Location.find_by(name: location)
        if location_object 
            params[:post][:location_id] = location_object.id
        else
            location_object = Location.create(name: location, city_id: city_object.id)
            params[:post][:location_id] = location_object.id
            params[:post][:city_id] = city_object.id
        end
        params
    end

    def post_params
        params.require(:post).permit(:caption, :image_url, :user_id, :location_id, :avatar)
    end

    def search(params)
        results_array = []
        query = params[:q]
        results_array << Post.where("caption ilike ?", "%#{query}%")
        locations = Location.where("name ilike ?", "%#{query}%")
        locations.each do |location|
            results_array << Post.all.select{|post| post.location == location}
        end
        cities = City.where("name ilike ?", "%#{query}%")
        cities.each do |city|
            results_array << Post.all.select{|post| post.location.city == city}
        end
        users = User.where("username ilike ?", "%#{query}%")
        users.each do |user|
            results_array << user.posts
        end
        results_array.flatten.uniq     
    end

    def require_login
        if !session[:user_id]
            redirect_to login_path
        end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="newbackground">
        <div class="newbody">
        <p id="flash">
        <%=flash[:user_error]%>
        <%flash.clear%>
        </p>
        <h1 class="newh1">Edit post</h1>
        </br>
        </br>
        <%=form_for @post do |f|%>
        <br>
        <%=f.label "Caption this picture!"%><br>
        <br>
        <%=f.text_area :caption %><br>
        <br>
        <%=f.hidden_field :user_id, :value => current_user.id%><br>
        <br>
        <%=f.label "location_id"%><br>
        <%=f.text_field :location_id, :value => @post.location.name.titleize, :class => "newinput"%><br>
        <br>
        <%=f.label "city_id"%><br>
        <%=f.text_field :city_id, :value => @post.location.city.name.titleize, :class => "newinput"%><br>
        <br>
        <%=f.submit%>
        <%end%>
        </div>
    </div>

app/views/posts/index.html.erb
<div class="index">
    <%posts =@posts.reject(&:blank?)%>
    <%if posts != []%>
        <%posts.each do |post|%>
            <%=link_to image_tag(url_for(post.avatar)), post_path(post), :class=>"linktoimage"%>
        <%end%>
    <%else%>
        <div class="noresult" id="nosearch">There were no results for that search</div>
    <%end%>
</div>

app/views/posts/new.html.erb
<div class="newbackground">
    <div class="newbody">
    <p id="flash">
    <%=flash[:user_error]%>
    <%flash.clear%>
    </p>
    <h1 class="newh1">Create a new post</h1>
    </br>
    </br>
    <%=form_for @post do |f|%>
    <%=f.label "Upload Image:"%><br>
    <br>
    <%=f.file_field :avatar , :id => "post_content"%><br>
    <br>
    <br>
    <br>
    <%=f.label "Caption this picture!"%><br>
    <br>
    <%=f.text_area :caption %><br>
    <%=f.hidden_field :user_id, :value => current_user.id%><br>
    <br>
    <%=f.label "location_id"%><br>
    <%=f.text_field :location_id, :class => "newinput"%><br>
    <br>
    <%=f.label "city_id"%><br>
    <%=f.text_field :city_id, :class => "newinput"%><br>
    <br>
    <%=f.submit :class => "inputbutton"%>
    <%end%>
    </div>
</div>

app/views/posts/show.html.erb
<div id="showbackground">
<div class="showbody">
    <div class="showimg">
        <h1 id="post_username"><%=link_to @post.user.username, user_path(@post.user)%>
            <span class="imagetag">
                &nbsp;
                &#8226;
                <%=link_to @post.location.name.titleize, location_path(@post.location)%>
                ,
                <%=link_to @post.location.city.name.titleize, city_path(@post.location.city)%>
            </span>
            <br>
            <br>
        </h1>
        <br>
        <br>
        <%=image_tag(url_for(@post.avatar))%>
        <br>
        <br>
        <h3>
        <%=@post.caption%>
        </br>
        <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %><br>
        <% if pre_like %>
          <%= link_to '❤️', post_like_path(@post, pre_like), method: :delete %>
        <% else %>
          <%= link_to '♡', post_likes_path(@post), method: :post %>
        <% end %>
        <%= @post.likes.count %>

        <%if @post.user.id == current_user.id%>
            <%=button_to "Delete Post", {:controller => :posts, :action => 'destroy', :post_id => @post.id}, :method => :delete, :class => "inputbutton"%>
            <%=button_to "Edit Post", {:controller => 'posts', :action=> 'edit', :id => @post.id}, :method => :get, :class => "inputbutton"%>
        <%end%>

        </h3>
    </div>
</div>
</div>