config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :cities
  resources :locations
  resources :posts
  # get '/travelgram', to: 'users#travelgram', as: "travelgram" 
  # get '/', to: 'users#travelgram'
  # post '/authenticate', to: "users#authenticate", as: "authenticate"
  resources :posts do
    resources :likes
  end 
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/login', to: 'sessions#destroy', as: "logout"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/search', to: 'posts#index', as: 'search'
  root 'sessions#new'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
    <title>CityFeed</title>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <div class="Header">
      <span id="logo"><%=link_to " 📸 CityFeed", posts_path%></span>
      <div class="search">
          <!-- <input type="text" placeholder="Search.." id="headersearch">
          <input type="submit" action="<%=posts_path%>" method="GET" id="searchsubmit" value="&#8981"> -->
          <% if logged_in? %>
          <%= form_tag("/search", method: "get", :id => 'headersearch') do %>
          <%= text_field_tag(:q, nil, :placeholder => "Search..") %>
          <%= submit_tag("  Search  ", class: "headersubmit")%>
          <div class="menubar">
                <a href="<%= user_path(current_user) %>">Profile</a>
                <%= link_to 'Logout', logout_path, {class: 'item', method: :delete} %>
              <% end %>
            </div>
        <% end %>
      </div>
    </div>
  </head>

  <body>
    <%= yield %>
  </body>
  <footer>
      <% unless current_page?(new_post_path) || current_page?(login_path) || current_page?(new_user_path)%>
      <div class="newpost">
          <a href="/posts/new">&#9532;</a>
          <%end%>
  </div>
  </footer>
</html>